### Site Settings ###
title               : Maddie Burbage
description         : >- 
    Developer. Researcher. Designer.
    Majoring in CS at Williams College, '22.
baseurl             : ""
repository          : maddieburbage/maddieburbage.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html


### Author Info ###
author:
  name              : Madeline Burbage
  image             : assets/head.jpg
  email             : maddie.grace32@yahoo.com
  github            : maddieburbage
  linkedin          : maddieburbage


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments



### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
